/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ReturnRefundRouteImport } from './routes/return-refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NightyRouteImport } from './routes/nighty'
import { Route as MenShirtsRouteImport } from './routes/men-shirts'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BedsheetsRouteImport } from './routes/bedsheets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminNavRouteImport } from './routes/_authenticated/admin.nav'
import { Route as AuthenticatedAdminBulkRouteImport } from './routes/_authenticated/admin.bulk'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminCollectionsIndexRouteImport } from './routes/_authenticated/admin.collections.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'
import { Route as AuthenticatedAdminCollectionsNewRouteImport } from './routes/_authenticated/admin.collections.new'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin.blog.new'
import { Route as AuthenticatedAdminCollectionsEditIdRouteImport } from './routes/_authenticated/admin.collections.edit.$id'
import { Route as AuthenticatedAdminBlogEditIdRouteImport } from './routes/_authenticated/admin.blog.edit.$id'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRefundRoute = ReturnRefundRouteImport.update({
  id: '/return-refund',
  path: '/return-refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NightyRoute = NightyRouteImport.update({
  id: '/nighty',
  path: '/nighty',
  getParentRoute: () => rootRouteImport,
} as any)
const MenShirtsRoute = MenShirtsRouteImport.update({
  id: '/men-shirts',
  path: '/men-shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsheetsRoute = BedsheetsRouteImport.update({
  id: '/bedsheets',
  path: '/bedsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNavRoute = AuthenticatedAdminNavRouteImport.update({
  id: '/admin/nav',
  path: '/admin/nav',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBulkRoute = AuthenticatedAdminBulkRouteImport.update({
  id: '/admin/bulk',
  path: '/admin/bulk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCollectionsIndexRoute =
  AuthenticatedAdminCollectionsIndexRouteImport.update({
    id: '/admin/collections/',
    path: '/admin/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/admin/blog/',
    path: '/admin/blog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/admin/edit/$id',
    path: '/admin/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCollectionsNewRoute =
  AuthenticatedAdminCollectionsNewRouteImport.update({
    id: '/admin/collections/new',
    path: '/admin/collections/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/admin/blog/new',
    path: '/admin/blog/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCollectionsEditIdRoute =
  AuthenticatedAdminCollectionsEditIdRouteImport.update({
    id: '/admin/collections/edit/$id',
    path: '/admin/collections/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogEditIdRoute =
  AuthenticatedAdminBlogEditIdRouteImport.update({
    id: '/admin/blog/edit/$id',
    path: '/admin/blog/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bedsheets': typeof BedsheetsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/men-shirts': typeof MenShirtsRoute
  '/nighty': typeof NightyRoute
  '/privacy': typeof PrivacyRoute
  '/return-refund': typeof ReturnRefundRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/nav': typeof AuthenticatedAdminNavRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/collections/new': typeof AuthenticatedAdminCollectionsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/collections/': typeof AuthenticatedAdminCollectionsIndexRoute
  '/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/admin/collections/edit/$id': typeof AuthenticatedAdminCollectionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bedsheets': typeof BedsheetsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/men-shirts': typeof MenShirtsRoute
  '/nighty': typeof NightyRoute
  '/privacy': typeof PrivacyRoute
  '/return-refund': typeof ReturnRefundRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/nav': typeof AuthenticatedAdminNavRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/collections/new': typeof AuthenticatedAdminCollectionsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsIndexRoute
  '/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/admin/collections/edit/$id': typeof AuthenticatedAdminCollectionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bedsheets': typeof BedsheetsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/men-shirts': typeof MenShirtsRoute
  '/nighty': typeof NightyRoute
  '/privacy': typeof PrivacyRoute
  '/return-refund': typeof ReturnRefundRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/_authenticated/admin/nav': typeof AuthenticatedAdminNavRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/collections/new': typeof AuthenticatedAdminCollectionsNewRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/collections/': typeof AuthenticatedAdminCollectionsIndexRoute
  '/_authenticated/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/_authenticated/admin/collections/edit/$id': typeof AuthenticatedAdminCollectionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bedsheets'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/men-shirts'
    | '/nighty'
    | '/privacy'
    | '/return-refund'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/admin/announcements'
    | '/admin/bulk'
    | '/admin/nav'
    | '/admin/new'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/tags'
    | '/admin/'
    | '/admin/blog/new'
    | '/admin/collections/new'
    | '/admin/edit/$id'
    | '/admin/blog/'
    | '/admin/collections/'
    | '/admin/blog/edit/$id'
    | '/admin/collections/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bedsheets'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/men-shirts'
    | '/nighty'
    | '/privacy'
    | '/return-refund'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/products/$slug'
    | '/blog'
    | '/products'
    | '/admin/announcements'
    | '/admin/bulk'
    | '/admin/nav'
    | '/admin/new'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/tags'
    | '/admin'
    | '/admin/blog/new'
    | '/admin/collections/new'
    | '/admin/edit/$id'
    | '/admin/blog'
    | '/admin/collections'
    | '/admin/blog/edit/$id'
    | '/admin/collections/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bedsheets'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/men-shirts'
    | '/nighty'
    | '/privacy'
    | '/return-refund'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/bulk'
    | '/_authenticated/admin/nav'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/collections/new'
    | '/_authenticated/admin/edit/$id'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/collections/'
    | '/_authenticated/admin/blog/edit/$id'
    | '/_authenticated/admin/collections/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BedsheetsRoute: typeof BedsheetsRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MenShirtsRoute: typeof MenShirtsRoute
  NightyRoute: typeof NightyRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnRefundRoute: typeof ReturnRefundRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-refund': {
      id: '/return-refund'
      path: '/return-refund'
      fullPath: '/return-refund'
      preLoaderRoute: typeof ReturnRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nighty': {
      id: '/nighty'
      path: '/nighty'
      fullPath: '/nighty'
      preLoaderRoute: typeof NightyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men-shirts': {
      id: '/men-shirts'
      path: '/men-shirts'
      fullPath: '/men-shirts'
      preLoaderRoute: typeof MenShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedsheets': {
      id: '/bedsheets'
      path: '/bedsheets'
      fullPath: '/bedsheets'
      preLoaderRoute: typeof BedsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/nav': {
      id: '/_authenticated/admin/nav'
      path: '/admin/nav'
      fullPath: '/admin/nav'
      preLoaderRoute: typeof AuthenticatedAdminNavRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bulk': {
      id: '/_authenticated/admin/bulk'
      path: '/admin/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AuthenticatedAdminBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/collections/': {
      id: '/_authenticated/admin/collections/'
      path: '/admin/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/admin/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/collections/new': {
      id: '/_authenticated/admin/collections/new'
      path: '/admin/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/collections/edit/$id': {
      id: '/_authenticated/admin/collections/edit/$id'
      path: '/admin/collections/edit/$id'
      fullPath: '/admin/collections/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog/edit/$id': {
      id: '/_authenticated/admin/blog/edit/$id'
      path: '/admin/blog/edit/$id'
      fullPath: '/admin/blog/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBulkRoute: typeof AuthenticatedAdminBulkRoute
  AuthenticatedAdminNavRoute: typeof AuthenticatedAdminNavRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminCollectionsNewRoute: typeof AuthenticatedAdminCollectionsNewRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminCollectionsIndexRoute: typeof AuthenticatedAdminCollectionsIndexRoute
  AuthenticatedAdminBlogEditIdRoute: typeof AuthenticatedAdminBlogEditIdRoute
  AuthenticatedAdminCollectionsEditIdRoute: typeof AuthenticatedAdminCollectionsEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBulkRoute: AuthenticatedAdminBulkRoute,
  AuthenticatedAdminNavRoute: AuthenticatedAdminNavRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
  AuthenticatedAdminCollectionsNewRoute: AuthenticatedAdminCollectionsNewRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminCollectionsIndexRoute:
    AuthenticatedAdminCollectionsIndexRoute,
  AuthenticatedAdminBlogEditIdRoute: AuthenticatedAdminBlogEditIdRoute,
  AuthenticatedAdminCollectionsEditIdRoute:
    AuthenticatedAdminCollectionsEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BedsheetsRoute: BedsheetsRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MenShirtsRoute: MenShirtsRoute,
  NightyRoute: NightyRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnRefundRoute: ReturnRefundRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  BlogSlugRoute: BlogSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
